name: Docker Build

on:
  workflow_dispatch:



jobs:
  type-check:
    name: Check Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'yarn'
      - name: Install Dependancies
        run: yarn install
      - name: Generate
        run: yarn generate
      - name: Build
        run: yarn tsc
  docker-build:
    runs-on: ubuntu-latest
    needs: 'type-check'
    name: 'Build and Publish Image'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/isd-workshop-09-group-02/backend
          # generate Docker tags based on the following events/attributes
          tags: |
            latest
            

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        id: docker_build
        with:
          context: .
          target: 'runner'
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
    