name: Build and Push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install Dependancies
        run: yarn install
      - name: Generate
        run: yarn generate
      - name: Test Frontend
        run: yarn workspace frontend tsc --noEmit
      - name: Test Backend
        run: yarn workspace backend tsc --noEmit